-- CreateTable
CREATE TABLE "Task" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ทำอยู่',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
